# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_client:
        default_options:
            headers:
                'Accepts': 'application/json'
                'X-CMC_PRO_API_KEY': '52a79d85-5703-4ba1-8b1c-600c03936e85'
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
